### ISSUE TITLE
Missing loadout at spawn

### ISSUE THREAD

**Issue by 68MrMercenary** [EmulatorNexus/VU-Docs#101]
Hi, I love this mod and all that Venice Unleashed has to offer the Battlefield 3 community. I am having a common random bug that when i spawn my loadout is absent and i can only see the crosshairs but no weapon in my loadout is visible. the only fix is to leave and rejoin my server. Is anyone else having this issue?
68MrMercenary

**Comment by FlashHit** [comment]
This is the wrong github page. 
Your issue is already known: https://github.com/EmulatorNexus/VeniceUnleashed/issues/722
Sadly we don’t really know what’s causing it nor how to fix it properly.

**Comment by 68MrMercenary** [comment]
> This is the wrong github page. Your issue is already known: [EmulatorNexus/VeniceUnleashed#722](https://github.com/EmulatorNexus/VeniceUnleashed/issues/722) Sadly we don’t really know what’s causing it nor how to fix it properly.

After switching to Fullscreen and not windowed mode my issue has not happened since. I tried to duplicate the issue in Fullscreen and it hasn't happened. Maybe its a bug in windowed mode?
thanks
