### ISSUE TITLE
gunSway [ReadOnly] isn't true

### ISSUE THREAD

**Issue by FlashHit** [EmulatorNexus/VU-Docs#11]
Here it says gunSway is read only but I edited it in a client mod so that's not true. Maybe it is read only serversided idk.
https://docs.veniceunleashed.net/vext/ref/shared/type/weaponfiring/

**Comment by OrfeasZ** [comment]
Read-only means that you cannot modify this specific property (eg. assign `nil` to it or a custom `GunSway` instance). It doesn't mean you can't modify the properties of its value.

**Comment by FlashHit** [comment]
ah alright, sorry then
