### ISSUE TITLE
Add note to run raycasts during UpdatePass_PreSim

### ISSUE THREAD

**Issue by kapraran** [EmulatorNexus/VU-Docs#28]
You may need to add a note for [`RaycastManager`](https://docs.veniceunleashed.net/vext/ref/client/library/raycastmanager) about when the methods of this class should be executed.

I had many crashes when i ran [`RaycastManager:Raycast`](https://docs.veniceunleashed.net/vext/ref/client/library/raycastmanager/#raycast) at random points in time. Then kiwidog suggested me to run raycasts during the [`UpdatePass_PreSim`](https://docs.veniceunleashed.net/vext/ref/fb/updatepass/) and it seems to does the trick.

```lua
Events:Subscribe('UpdateManager:Update', function(deltaTime, updatePass)
    if updatePass ~= UpdatePass.UpdatePass_PreSim then
      return
    end

    -- Raycasts should be here
end)
```

**Comment by kiwidoggie** [comment]
This has been noted in Vext documentation for 1.0.9
