### ISSUE TITLE
Winepath Instance Directory Needed

### ISSUE THREAD

**Issue by pro4tlzz** [EmulatorNexus/VU-Docs#39]
[> >### Running a VU server 
> You are now ready to run a VU server. To do so, use the command below:
> 
> wine ~/vu/client/vu.com -gamepath ~/bf3 -serverInstancePath ~/vu/instance -server -dedicated
> Your server will start up and will soon be joinable by players. It is recommended to restart your server every now and then so you can receive updates and fixes.](https://docs.veniceunleashed.net/hosting/setup-linux/)

This here for the Linux instructions seems wrong, I tried [this ](https://github.com/EmulatorNexus/VeniceUnleashed/issues/528)and it worked

**Comment by FlashHit** [comment]
this was fixed in https://github.com/EmulatorNexus/VU-Docs/pull/22
🤔
