### ISSUE TITLE
AimingSimulation can be nil as well

### ISSUE THREAD

**Issue by FlashHit** [EmulatorNexus/VU-Docs#43]
https://docs.veniceunleashed.net/vext/ref/client/type/soldierweapon/
The aimingSimulation of other players soldierWeapon is nil.

**Comment by kiwidoggie** [comment]
Fields for weaponModifier, correctedWeaponFiring, predictedWeaponFiring, and aimingSimulation have been updated to reflect properly in patch notes for vext 1.0.9
