### ISSUE TITLE
VU Documentation

### ISSUE THREAD

**Issue by JTiRonSiDe** [EmulatorNexus/VU-Docs#47]
![Screenshot_240](https://user-images.githubusercontent.com/76711210/103248516-a6836000-4949-11eb-9aba-db777bef6414.png)

How to solve? Help please!!!

**Comment by FlashHit** [comment]
This is the wrong place to ask. You should have used the forum or the right discord channel. 
anyways you didn’t provide any additional information next to the screenshot.
Did you create a server key and add it to the Server folder? Or did you try creating a new key?

**Comment by JTiRonSiDe** [comment]
I downloaded the VU and started it, and it was working normally and today when I went to play it gives me this error

**Comment by JTiRonSiDe** [comment]
sorry for the inconvenience, I already solved the problem !!!

**Comment by FlashHit** [comment]
Haha, np. So I guess you wanted to start the client but started a server instead

**Comment by JTiRonSiDe** [comment]
that's exactly what I was doing, hahahahah!
