### ISSUE TITLE
Server administration documentation needs clearer instruction paths

### ISSUE THREAD

**Issue by kiwidoggie** [EmulatorNexus/VU-Docs#5]
After having multiple people get stuck on setting up a server document, there needs to be a clear path of how to set up a server. Currently there is no easy way for someone not familiar with the BF3 server and VU to understand which wiki links are needed and which aren't. I will work on this and file a PR when complete.

**Comment by OrfeasZ** [comment]
The path is clearly defined as the server hosting guide is a collection of steps that need to be followed in sequence and covers everything from initial setup to configuration and remote administration.
