### ISSUE TITLE
Guid:ToString()

### ISSUE THREAD

**Issue by FlashHit** [EmulatorNexus/VU-Docs#7]
I think it should be mentioned that it needs to be Guid:ToString('D') to make it work. Took me a while to figure that out.

**Comment by Powback** [comment]
or tostring(guid)

**Comment by FlashHit** [comment]
Yea I used that one the whole time. But then what’s the point in having this extra method

**Comment by Powback** [comment]
Because the extra method allows you to specify formatting. We decided to stick with the dashed format by default though.

D = Dashed
N = No dashes
B = Dashed with Brackets
P = Dashed with Parenthesis

**Comment by OrfeasZ** [comment]
I've updated the documentation to include this missing parameter and also the missing constructor. See: https://docs.veniceunleashed.net/vext/ref/shared/type/guid/
